### ISSUE TITLE
dataset and fitting

### ISSUE THREAD

**Issue by titouanjehl** [carslawbroccoli/GA#1]
During the meeting, we simply discussed fitting a dataset.

We need some values that are function of the variable of the dataset for the fitting right?
For instance let X be the dataset and  f a function, we would have a Y vector such that its ith component is the evaluation of f on the ith line of X and some noise?

**Comment by carslawbroccoli** [comment]
I think we have the Y vector from the data since the dataset (regression/GLM) will come with the Y value. So I suggest that the input variables X and Y could be a matrix. The Y vector is one of the columns(usually the last column) of the matrix.
